### PR TITLE
Ibtissam week 1 tasks

### PR DESCRIPTION
**Pull request by ibtissambekk87**
here are tasks java for week 1

### CODE REVIEW

**Review by VitoriaDullius — COMMENTED** [review]
Hey Ibtissam, I believe you need to create a method for each one of the tasks, you just did the main method. Let me know if you need any help :)

**Comment by ibtissambekk87** [comment]
ok i will modify them thanks

**Comment by ibtissambekk87** [comment]
hi Vitoria i added the updated version of tasks.

**Review by VitoriaDullius — APPROVED** [review]
Hey well done!!

**Pull request closed without merging**
